const movies = [
  {
    id: 1,
    title: "Inception",
    year: 2010,
    rating: 8.8,
    genres: ["Sci-Fi", "Thriller", "Action"],
    tags: ["dream", "heist", "mind-bending", "psychological", "layered reality"],
    description: "A thief who steals corporate secrets through dream-sharing technology is given the task of planting an idea into a CEO's mind.",
    poster: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    director: "Christopher Nolan"
  },
  {
    id: 2,
    title: "Interstellar",
    year: 2014,
    rating: 8.6,
    genres: ["Sci-Fi", "Drama", "Adventure"],
    tags: ["space", "time", "wormhole", "survival", "father-daughter", "relativity"],
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    director: "Christopher Nolan"
  },
  {
    id: 3,
    title: "The Dark Knight",
    year: 2008,
    rating: 9.0,
    genres: ["Action", "Crime", "Drama"],
    tags: ["superhero", "batman", "joker", "chaos", "vigilante", "moral dilemma"],
    description: "Batman faces the Joker, a criminal mastermind who wants to plunge Gotham City into anarchy.",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    director: "Christopher Nolan"
  },
  {
    id: 4,
    title: "The Matrix",
    year: 1999,
    rating: 8.7,
    genres: ["Sci-Fi", "Action"],
    tags: ["simulation", "reality", "hacker", "AI", "dystopia", "mind-bending"],
    description: "A hacker discovers that reality as he knows it is a simulation and joins a rebellion against its machine overlords.",
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    director: "The Wachowskis"
  },
  {
    id: 5,
    title: "Parasite",
    year: 2019,
    rating: 8.5,
    genres: ["Drama", "Thriller", "Comedy"],
    tags: ["class", "social inequality", "family", "deception", "dark humor", "Korean"],
    description: "A poor family schemes to become employed by a wealthy family and infiltrate their household.",
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    director: "Bong Joon-ho"
  },
  {
    id: 6,
    title: "Pulp Fiction",
    year: 1994,
    rating: 8.9,
    genres: ["Crime", "Drama", "Thriller"],
    tags: ["nonlinear", "crime", "hitman", "violence", "cult classic", "dialogue"],
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in a series of tales of violence and redemption.",
    poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    director: "Quentin Tarantino"
  },
  {
    id: 7,
    title: "Avengers: Endgame",
    year: 2019,
    rating: 8.4,
    genres: ["Action", "Adventure", "Sci-Fi"],
    tags: ["superhero", "marvel", "time travel", "battle", "thanos", "epic"],
    description: "After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos's actions.",
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    director: "Anthony & Joe Russo"
  },
  {
    id: 8,
    title: "The Shawshank Redemption",
    year: 1994,
    rating: 9.3,
    genres: ["Drama"],
    tags: ["prison", "hope", "friendship", "escape", "redemption", "wrongful conviction"],
    description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    poster: "https://image.tmdb.org/t/p/w500/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
    director: "Frank Darabont"
  },
  {
    id: 9,
    title: "Spirited Away",
    year: 2001,
    rating: 8.6,
    genres: ["Animation", "Adventure", "Fantasy"],
    tags: ["anime", "spirit world", "coming-of-age", "magical", "Japanese", "Miyazaki"],
    description: "A sullen 10-year-old girl wanders into a world ruled by gods, witches, and monsters.",
    poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    director: "Hayao Miyazaki"
  },
  {
    id: 10,
    title: "Forrest Gump",
    year: 1994,
    rating: 8.8,
    genres: ["Drama", "Romance", "Comedy"],
    tags: ["life journey", "historical events", "kindness", "love", "destiny", "American history"],
    description: "The presidencies of Kennedy and Johnson, Vietnam, Watergate and other history unfold through the perspective of an Alabama man.",
    poster: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    director: "Robert Zemeckis"
  },
  {
    id: 11,
    title: "Joker",
    year: 2019,
    rating: 8.4,
    genres: ["Crime", "Drama", "Thriller"],
    tags: ["origin story", "mental illness", "society", "chaos", "Gotham", "villain"],
    description: "A failed comedian is driven to insanity and becomes a criminal mastermind in a corrupt Gotham City.",
    poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    director: "Todd Phillips"
  },
  {
    id: 12,
    title: "Dune",
    year: 2021,
    rating: 8.0,
    genres: ["Sci-Fi", "Adventure", "Drama"],
    tags: ["desert", "prophecy", "empire", "spice", "epic", "chosen one"],
    description: "Paul Atreides leads nomadic tribes in a battle to control the desert planet Arrakis.",
    poster: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    director: "Denis Villeneuve"
  },
  {
    id: 13,
    title: "The Godfather",
    year: 1972,
    rating: 9.2,
    genres: ["Crime", "Drama"],
    tags: ["mafia", "family", "power", "loyalty", "crime", "classic"],
    description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLMdL73KsPyd.jpg",
    director: "Francis Ford Coppola"
  },
  {
    id: 14,
    title: "Get Out",
    year: 2017,
    rating: 7.7,
    genres: ["Horror", "Mystery", "Thriller"],
    tags: ["racism", "psychological", "twist", "social commentary", "paranoia"],
    description: "A young African-American visits his white girlfriend's parents for the weekend, where his unease grows.",
    poster: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    director: "Jordan Peele"
  },
  {
    id: 15,
    title: "La La Land",
    year: 2016,
    rating: 8.0,
    genres: ["Drama", "Music", "Romance"],
    tags: ["jazz", "dreams", "Los Angeles", "musical", "bittersweet", "aspiration"],
    description: "A jazz musician and an aspiring actress fall in love in Los Angeles while pursuing their dreams.",
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    director: "Damien Chazelle"
  },
  {
    id: 16,
    title: "Mad Max: Fury Road",
    year: 2015,
    rating: 8.1,
    genres: ["Action", "Adventure", "Sci-Fi"],
    tags: ["post-apocalyptic", "survival", "chase", "dystopia", "female empowerment", "wasteland"],
    description: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in a high-speed chase.",
    poster: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
    director: "George Miller"
  },
  {
    id: 17,
    title: "Her",
    year: 2013,
    rating: 8.0,
    genres: ["Drama", "Romance", "Sci-Fi"],
    tags: ["AI", "loneliness", "relationship", "future", "technology", "emotional"],
    description: "A lonely writer develops an unlikely relationship with an AI operating system.",
    poster: "https://image.tmdb.org/t/p/w500/eCOtqtfvn7mxGaRbOH3hS4GqCqx.jpg",
    director: "Spike Jonze"
  },
  {
    id: 18,
    title: "Whiplash",
    year: 2014,
    rating: 8.5,
    genres: ["Drama", "Music"],
    tags: ["jazz", "obsession", "ambition", "music school", "perfectionism", "drummer"],
    description: "A promising young drummer enrolls at a cut-throat music conservatory where his instructor will stop at nothing to realize a student's potential.",
    poster: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    director: "Damien Chazelle"
  },
  {
    id: 19,
    title: "The Silence of the Lambs",
    year: 1991,
    rating: 8.6,
    genres: ["Crime", "Drama", "Thriller"],
    tags: ["serial killer", "FBI", "psychological", "suspense", "Hannibal Lecter", "detective"],
    description: "A young FBI cadet must receive the help of an imprisoned and manipulative cannibal killer to help catch another serial killer.",
    poster: "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    director: "Jonathan Demme"
  },
  {
    id: 20,
    title: "Blade Runner 2049",
    year: 2017,
    rating: 8.0,
    genres: ["Sci-Fi", "Drama", "Mystery"],
    tags: ["dystopia", "AI", "replicant", "future", "neo-noir", "identity"],
    description: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard.",
    poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    director: "Denis Villeneuve"
  },
  {
    id: 21,
    title: "Coco",
    year: 2017,
    rating: 8.4,
    genres: ["Animation", "Adventure", "Family"],
    tags: ["music", "family", "Mexico", "Day of the Dead", "heritage", "dreams"],
    description: "A young boy who dreams of becoming a musician goes on a journey to the Land of the Dead.",
    poster: "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
    director: "Lee Unkrich"
  },
  {
    id: 22,
    title: "1917",
    year: 2019,
    rating: 8.3,
    genres: ["Action", "Drama", "War"],
    tags: ["World War I", "single take", "mission", "survival", "soldiers", "British"],
    description: "Two British soldiers are sent on a treacherous mission to deliver a message that could save 1,600 lives.",
    poster: "https://image.tmdb.org/t/p/w500/iZf0KyrE25z1sage4SYFLCCrMi9.jpg",
    director: "Sam Mendes"
  },
  {
    id: 23,
    title: "Knives Out",
    year: 2019,
    rating: 7.9,
    genres: ["Crime", "Drama", "Mystery"],
    tags: ["whodunit", "detective", "family", "twist", "inheritance", "comedy"],
    description: "A detective investigates the death of a patriarch of an eccentric, combative family.",
    poster: "https://image.tmdb.org/t/p/w500/pThyQovXQrpS2NnkXaBDWw7v4XT.jpg",
    director: "Rian Johnson"
  },
  {
    id: 24,
    title: "Tenet",
    year: 2020,
    rating: 7.3,
    genres: ["Action", "Sci-Fi", "Thriller"],
    tags: ["time inversion", "espionage", "mind-bending", "palindrome", "future", "spy"],
    description: "A secret agent embarks on a dangerous mission through time manipulation to prevent World War III.",
    poster: "https://image.tmdb.org/t/p/w500/k68nPLbIST6NP96JmTxmZijAbga.jpg",
    director: "Christopher Nolan"
  },
  {
    id: 25,
    title: "Everything Everywhere All at Once",
    year: 2022,
    rating: 7.8,
    genres: ["Action", "Adventure", "Comedy", "Sci-Fi"],
    tags: ["multiverse", "family", "absurdist", "A24", "identity", "mother-daughter"],
    description: "A middle-aged Chinese immigrant is swept up in an insane adventure to save the multiverse.",
    poster: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    director: "Daniel Kwan & Daniel Scheinert"
  },
  {
    id: 26,
    title: "No Country for Old Men",
    year: 2007,
    rating: 8.1,
    genres: ["Crime", "Drama", "Thriller"],
    tags: ["violence", "fate", "Texas", "bounty hunter", "nihilism", "pursuit"],
    description: "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and takes the money.",
    poster: "https://image.tmdb.org/t/p/w500/6ROiMnrWKOt3WlLzm4bGQ4oGyCL.jpg",
    director: "Joel & Ethan Coen"
  },
  {
    id: 27,
    title: "The Grand Budapest Hotel",
    year: 2014,
    rating: 8.1,
    genres: ["Adventure", "Comedy", "Crime"],
    tags: ["quirky", "Wes Anderson", "heist", "Europe", "murder mystery", "stylized"],
    description: "A writer encounters the owner of an aging European hotel who tells him of his youth managing the property and his friendship with a concierge.",
    poster: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    director: "Wes Anderson"
  },
  {
    id: 28,
    title: "Arrival",
    year: 2016,
    rating: 7.9,
    genres: ["Drama", "Mystery", "Sci-Fi"],
    tags: ["aliens", "language", "time", "linguistics", "communication", "thoughtful"],
    description: "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
    poster: "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
    director: "Denis Villeneuve"
  },
  {
    id: 29,
    title: "Oldboy",
    year: 2003,
    rating: 8.4,
    genres: ["Action", "Drama", "Mystery", "Thriller"],
    tags: ["revenge", "mystery", "twist", "Korean", "prison", "dark"],
    description: "After being imprisoned in a cell for 15 years without explanation, a man is released and given 5 days to discover who imprisoned him.",
    poster: "https://image.tmdb.org/t/p/w500/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg",
    director: "Park Chan-wook"
  },
  {
    id: 30,
    title: "WALL-E",
    year: 2008,
    rating: 8.4,
    genres: ["Animation", "Adventure", "Family", "Romance", "Sci-Fi"],
    tags: ["robot", "love", "space", "environment", "future", "Pixar", "silent film"],
    description: "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will determine the fate of mankind.",
    poster: "https://image.tmdb.org/t/p/w500/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
    director: "Andrew Stanton"
  }
];
